<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQIxe5xk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQIxe5xk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQIxe5xk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQIxe5xk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQIxe5xk\App_KernelDevDebugContainer([
    'container.build_hash' => 'QIxe5xk',
    'container.build_id' => '95b36e07',
    'container.build_time' => 1619773105,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQIxe5xk');
