<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMOUZAhL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMOUZAhL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMOUZAhL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMOUZAhL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMOUZAhL\App_KernelDevDebugContainer([
    'container.build_hash' => 'MOUZAhL',
    'container.build_id' => '1c7a6c21',
    'container.build_time' => 1621337590,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMOUZAhL');
